#!/bin/bash


curmac=$(ifconfig en0 | grep ether)
oldmac=$(echo $curmac | sed "s/ether//")
echo $oldmac > oldmac.txt

mac=$(openssl rand -hex 6 | sed 's/\(..\)/\1:/g; s/.$//')
sudo ifconfig en0 down
sudo ifconfig en0 up
sleep 1
sudo ifconfig en0 ether $mac

echo "Old MAC: $oldmac"
echo "New MAC: $mac"
